### ISSUE TITLE
Changes in the get-purchase-orders() API.

### ISSUE THREAD

**Issue by ssvillarosa** [PUP-BSIT/project-wibs#2]
Kindly note the changes in the API that I made. See the change below:
![customer update](https://github.com/PUP-BSIT/project-wibs/assets/76401444/f0fe2e18-1d75-4a2c-9fdb-ea770552c59f)

This change is necessary to cater the needed data from the seller part. Kindly coordinate with them. Kindly update your database schema to accommodate the changes.

**Comment by alejandro-andreijames** [comment]
This is noted po Sir.

**Comment by calderonpearl** [comment]
We acknowledge this adjustment, sir, and we will incorporate the suggested changes accordingly. Thank you!
